-- Common DDL Commands: CREATE, ALTER, DROP, TRUNCATE

-- Drop table

-- DROP TABLE public.order_table;
-- DROP TABLE public.notification_table;
-- DROP TABLE public.retrieve_table;
-- DROP TABLE public.order_transactions;


CREATE TABLE public.order_table (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	channel varchar(50) NULL,
	client varchar(50) NULL,
	distribution_id varchar(50) NULL,
	job_name varchar(50) NULL,
	orderdata text NULL,
	orderid varchar(50) NOT NULL,
	recieved_time timestamptz DEFAULT now() NOT NULL,
	status varchar(50) NULL,
	updated_time timestamptz NULL,
	correlation_id varchar(100) NULL,
	traceid varchar(100) NULL,
	print_flag varchar(50) NULL,
	error_message varchar(250) NULL,
	CONSTRAINT order_table_pkey PRIMARY KEY (id)
);

ALTER TABLE public.order_table OWNER TO "DBUser";
GRANT ALL ON TABLE public.order_table TO "DBUser";


CREATE TABLE public.notification_table (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id varchar(50) NULL,
	message_data text NULL,
	orderid varchar(50) NULL,
	recieved_time timestamptz DEFAULT now() NOT NULL,
	status varchar(50) NULL,
	correlation_id varchar(100) NULL,
	process_count int4 DEFAULT 1 NULL,
	updated_time timestamptz NULL,
	CONSTRAINT notification_table_pkey PRIMARY KEY (id)
);

ALTER TABLE public.notification_table OWNER TO "DBUser";
GRANT ALL ON TABLE public.notification_table TO "DBUser";


CREATE TABLE public.retrieve_table (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	client varchar(50) NULL,
	correlation_id varchar(100) NULL,
	message_data text NULL,
	orderid varchar(50) NULL,
	recieved_time timestamptz DEFAULT now() NOT NULL,
	s3location varchar(250) NULL,
	status varchar(50) NULL,
	document_id varchar(50) NULL,
	updated_time timestamptz NULL,
	process_count int4 DEFAULT 1 NULL,
	CONSTRAINT retrieve_table_pkey PRIMARY KEY (id)
);

ALTER TABLE public.retrieve_table OWNER TO "DBUser";
GRANT ALL ON TABLE public.retrieve_table TO "DBUser";


CREATE TABLE public.order_transactions (
	id bigserial NOT NULL,
	orderid varchar(50) NOT NULL,
	transactionid varchar(50) NOT NULL,
	client varchar(50) NOT NULL,
	recieved_time timestamptz DEFAULT now() NOT NULL,
	updated_time timestamptz NULL,
	CONSTRAINT order_transactions_pkey PRIMARY KEY (id)
);

ALTER TABLE public.order_transactions OWNER TO "DBUser";
GRANT ALL ON TABLE public.order_transactions TO "DBUser";


CREATE TABLE public.contact_details (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NULL,
	first_name varchar(50) NULL,
	last_name varchar(50) NULL,
	address_line1 varchar(100) NULL,
	address_line2 varchar(100) NULL,
	city varchar(50) NULL,
	country varchar(50) NULL,
	orderid varchar(50) NULL,
	province_country varchar(50) NULL,
	value varchar(50) NULL,
	zip_code varchar(8) NULL,
	CONSTRAINT contact_details_pkey PRIMARY KEY (id)
);


-- Order_Table Triggers
	
CREATE OR REPLACE FUNCTION update_timestamp_ordertable()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_timestamp_ordertable ON public.order_table;

CREATE TRIGGER trigger_update_timestamp_ordertable
BEFORE UPDATE ON public.order_table
FOR EACH ROW
EXECUTE FUNCTION update_timestamp_ordertable();

-- Notification_Table Triggers

CREATE OR REPLACE FUNCTION update_timestamp_notificationtable()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_timestamp_notificationtable ON public.notification_table;

CREATE TRIGGER trigger_update_timestamp_notificationtable
BEFORE UPDATE ON public.notification_table
FOR EACH ROW
EXECUTE FUNCTION update_timestamp_notificationtable();

-- Retrieve_Table Triggers

CREATE OR REPLACE FUNCTION update_timestamp_retrievetable()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_timestamp_retrievetable ON public.retrieve_table;

CREATE TRIGGER trigger_update_timestamp_retrievetable
BEFORE UPDATE ON public.retrieve_table
FOR EACH ROW
EXECUTE FUNCTION update_timestamp_retrievetable();

-- Retrieve_Table Triggers

CREATE OR REPLACE FUNCTION update_timestamp_ordertransactions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_timestamp_ordertransactions ON public.order_transactions;

CREATE TRIGGER trigger_update_timestamp_ordertransactions
BEFORE UPDATE ON public.order_transactions
FOR EACH ROW
EXECUTE FUNCTION update_timestamp_ordertransactions();

